export const skillsList = {
  'Programming Languages': ['TypeScript', 'JavaScript', 'Python', 'C++', 'C', 'Bash', 'HTML', 'CSS'],
  'Operating Systems': ['Linux', 'Unix', 'Windows', 'macOS'],
  'Networking': ['Routers', 'Switches', 'VPNs', 'Layer 2/3', 'TCP/IP', 'DHCP', 'Subnetting', 'DNS', 'SNMP'],
  'Software/Frameworks': [
    'React',
    'Node.js',
    'Next.js',
    'React Native',
    'Redux',
    'Elasticsearch',
    'Material UI (MUI)',
    'Selenium',
    'Docker',
    'Kubernetes',
    'Redis',
    'Kafka',
    'Kong',
    'PostgreSQL',
    'Git',
    'Jest',
    'GitHub',
    'GitLab',
    'CI/CD',
    'Postman',
    'Figma',
    'JSON',
    'XML',
    'YAML',
    'Yang',
  ],
  'Amazon Web Services': [
    'Lambda',
    'DynamoDB',
    'CloudWatch',
    'IAM',
    'S3',
    'IoT',
    'Cognito',
    'Amplify',
    'Route 53',
    'API Gateway',
    'EC2',
    'ECS',
    'EKS',
    'ECR',
  ],
  'Foreign Languages': ['English (Fluent)', 'Russian (Fluent)', 'Spanish (Light conversation)'],
};

export const hobbiesList = [
  'Problem Solving',
  'Hiking',
  'Working Out',
  'Traveling',
  'Hanging with Friends and Family',
  'Cooking',
  'Gaming',
  'Golfing',
  'Soccer',
  'Ravens Football',
];
